apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  namespace: diplom-site
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: diplom-simple-site
          image: cr.yandex/crpbskr2qmiqq3bbf2b2/app/site:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ycr-json-key