apiVersion: v1
kind: Service
metadata:
  name: simple-site-service
  namespace: diplom-site
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30051