#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - python3
  - python3-pip
  - python3.12-venv
  - git
  - gnupg
  - curl

runcmd:
  # Установка kubectl
  - curl -LO "https://dl.k8s.io/release/v1.30.14/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - rm -f kubectl
  # Установка Helm
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  # подготовка к установке kubespray
  - cd /home/ubuntu
  - git clone https://github.com/kubernetes-sigs/kubespray.git
  - chown -R ubuntu:ubuntu /home/ubuntu/kubespray
