#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - python3.12-venv
  - git
  - curl

runcmd:
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - cd /home/ubuntu
  - git clone https://github.com/kubernetes-sigs/kubespray.git
  - chown -R ubuntu:ubuntu /home/ubuntu/kubespray
