#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - git
  - curl
  - jq

runcmd:
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - cd /home/ubuntu
  - git clone https://github.com/kubernetes-sigs/kubespray.git
  - cd kubespray
  - python3 -m venv venv
  - . venv/bin/activate && pip install -U pip && pip install -r requirements.txt
  - chown -R ubuntu:ubuntu /home/ubuntu
