#cloud-config
package_update: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - curl
  - tar

runcmd:
  # Установка pip и Ansible
  # - pip3 install --upgrade pip
  # - pip3 install ansible

  # Установка Helm (последняя версия)
  - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  # Клонирование kubespray в /home/ubuntu
  - git clone https://github.com/kubernetes-sigs/kubespray.git /home/ubuntu/kubespray

  # Создание и активация Python venv
  - python3 -m venv /home/ubuntu/kubespray/venv
  - /home/ubuntu/kubespray/venv/bin/pip install --upgrade pip
  - /home/ubuntu/kubespray/venv/bin/pip install -r /home/ubuntu/kubespray/requirements.txt

  # Ссылка на cluster.yml
  # - ln -s /home/ubuntu/kubespray/cluster.yml /home/ubuntu/cluster.yml

  # Автоактивация virtualenv в .bashrc
  # - echo 'source /home/ubuntu/kubespray/venv/bin/activate' >> /home/ubuntu/.bashrc

  # Права
  - chown -R ubuntu:ubuntu /home/ubuntu/kubespray
  # - chown ubuntu:ubuntu /home/ubuntu/cluster.yml
  # - chown ubuntu:ubuntu /home/ubuntu/.bashrc
