all:
  hosts:
    master:
      ansible_host: 89.169.155.214
      ip: 10.0.2.31
      kube_apiserver_ip: 89.169.155.214
    worker-1:
      ansible_host: 51.250.100.154
      ip: 10.0.3.36
    worker-2:
      ansible_host: 89.169.174.44
      ip: 10.0.3.8
    worker-3:
      ansible_host: 84.252.142.218
      ip: 10.0.3.28
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
        worker-3:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}