all:
  hosts:
    master-1:
      ansible_host: 89.169.135.209
      ip: 10.0.2.12
      access_ip: 89.169.135.209
      kube_apiserver_ip: 89.169.135.209
    worker-1:
      ansible_host: 84.252.142.60
      ip: 10.0.3.10
    worker-2:
      ansible_host: 89.169.176.67
      ip: 10.0.3.9
    worker-3:
      ansible_host: 84.252.143.239
      ip: 10.0.3.23
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
        worker-3:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}